-- Création de la base de données "CHURN_CUSTOMER_DB"
-- DROP DATABASE IF EXISTS "CHURN_CUSTOMER_DB";
-- CREATE DATABASE "CHURN_CUSTOMER_DB";


-- Création du schéma CHURN_CUSTOMER_DWH
DROP SCHEMA IF EXISTS "CHURN_CUSTOMER_DWH";
CREATE SCHEMA "CHURN_CUSTOMER_DWH";