-- Création du schéma CHURN_CUSTOMER_DWH
-- DROP SCHEMA IF EXISTS "CHURN_CUSTOMER_DWH" CASCADE;
CREATE SCHEMA IF NOT EXISTS "CHURN_DWH";

-- Création du schéma PARAMS_LOG
-- DROP SCHEMA IF EXISTS "PARAMS_LOG" CASCADE;
CREATE SCHEMA IF NOT EXISTS "PARAMS_LOG";